model: 'faster_rcnn'
architecture: 'resnet101'
checkpoint_path: '/network/scratch/a/arthur.ouaknine/logs/detection/quebec_trees/fasterrcnn/resnet101/trim-blaze-3/checkpoints/checkpoint_iter_00072000.pt'
batch_size: 5
num_classes: 19
box_predictions_per_image: 500
