components_configs:
  - tilerizer: rubisco_inference/tilerizer_detector
  - detector: rubisco_inference/detector
  - aggregator: rubisco_inference/aggregator_detector
  - tilerizer: rubisco_inference/tilerizer_segmenter
  - segmenter: rubisco_inference/segmenter
  - aggregator: rubisco_inference/aggregator_segmenter
  - rubisco_db_writer: rubisco_inference/rubisco_db_writer