model: 'dino_detrex'
architecture: ''
checkpoint_path: '/home/hugo/Downloads/dino_r50_4scale_24ep.pth'
batch_size: 1
num_classes: 1
box_predictions_per_image: null
box_score_thresh: null
box_nms_thresh: null

# Training Data and Output path
data_root_path: '/mnt/disk2/Data/tilerized'
train_dataset_names: ['panama_bci50ha', 'ecuador_reforestree']
train_output_path: './output/detrex_dino_r50_4scale_24ep_2'

# Training Params
#main_metric: 'mAP'
seed: 0
wandb_project: 'neurips_d&b_detector'

augmentation_image_size: 1024     # Final image size for both training and evaluation
augmentation_train_crop_size_range: [784, 2048]
augmentation_crop_min_intersection_ratio: 0.5
augmentation_flip_horizontal: True
augmentation_flip_vertical: True
augmentation_rotation: 30
augmentation_rotation_prob: 0.5
augmentation_contrast: 0.2
augmentation_brightness: 0.2
augmentation_saturation: 0.2

lr: null
max_epochs: 100
freeze_layers: null
train_log_interval: 10
eval_epoch_interval: 1
#grad_accumulation_steps: 1
backbone_model_pretrained: null
scheduler_epochs_steps: null
scheduler_warmup_steps: null
scheduler_gamma: null
dataloader_num_workers: 4

use_gradient_checkpointing: null
use_amp: true