components_configs:
  - tilerizer: default_detection_multi_NQOS_best/tilerizer
  - detector: default_detection_multi_NQOS_best/detector
  - aggregator: default_detection_multi_NQOS_best/aggregator
  - segmenter: default_segmentation_multi_NQOS_best/segmenter
  - aggregator: default_segmentation_multi_NQOS_best/aggregator
